server {
  listen 8082;

  location / {
    proxy_pass http://localhost;
  }

  location /swagger.yaml {
    proxy_pass http://localhost/api/v1/swagger.yaml;
  }

  location /swagger-ui/ {
    proxy_pass http://localhost:8081/;
  }

}
