namespace CarbonAware.Interfaces;

public interface IHttpResponseException
{
    /// <summary>
    /// A short, human-readable summary of the problem type. It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    #nullable enable
    public string? Title { get; }
    #nullable disable

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int? Status { get; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    #nullable enable
    public string? Detail { get; }
    #nullable disable

    /// <summary>
    /// The HttpResponseMessage object responsible for raising this exception.
    /// </summary>
    #nullable enable
    public HttpResponseMessage? Response { get; }
    #nullable disable
}