/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.
.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.'
    },
    {
      type: 'category',
      label: 'API references for WebAPI client libraries',
      items: [
        {
          type: 'category',
          label: 'WebAPI 1.0.0',
          items: [
            {
              type: 'link',
              label: 'Java',
              href: 'https://carbon-aware-sdk.greensoftware.foundation/client-apidocs/1.0.0/java/'
            },
            {
              type: 'link',
              label: 'NPM',
              href: 'https://carbon-aware-sdk.greensoftware.foundation/client-apidocs/1.0.0/npm/'
            }
          ]
        },
      ]
    }
  ]
};

module.exports = sidebars;
