"""
    CarbonAware.WebApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.emissions_data_dto import EmissionsDataDTO


class TestEmissionsDataDTO(unittest.TestCase):
    """EmissionsDataDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmissionsDataDTO(self):
        """Test EmissionsDataDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmissionsDataDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
