"""
    CarbonAware.WebApi

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.carbon_intensity_batch_dto import CarbonIntensityBatchDTO


class TestCarbonIntensityBatchDTO(unittest.TestCase):
    """CarbonIntensityBatchDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCarbonIntensityBatchDTO(self):
        """Test CarbonIntensityBatchDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CarbonIntensityBatchDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
